### ISSUE TITLE
Pointer being freed was not allocated

### ISSUE THREAD

**Issue by amanbolat** [PerfectExamples/Perfect-Turnstile-PostgreSQL-Demo#1]
I tried to install this demo on my linux and mac machines. Sometimes it will cause error with message:

> PerfectTurnstilePostgreSQLDemo(88968,0x700003223000) malloc: **\* error for object 0x102110039: pointer being freed was not allocated

Error caused by this block of code:

/// Closes the connection to the server. Also frees memory used by the PGconn object.

```
public func finish() {
  if self.conn != nil {
    PQfinish(self.conn)
      self.conn = OpaquePointer(bitPattern: 0)
   }
}
```

**Comment by iamjono** [comment]
I haven't seen this myself - is there particular steps you can do to reproduce this so I can try to replicate and fix it?

**Comment by amanbolat** [comment]
It can happen just when i start server then go to 0.0.0.0:8181. Or when i used it for 1-3 minutes, registering new users, logging in and out, then in 20 minutes i do something again and this error come again. 

Also in debug i see that the connection variable is nil! But it is not correct, if statement should stop PQfinish from execution it. 

And i don't understand why connection variable in main.swift file is public var from PostgresSTorm.swift? Shouldn't we create a new `let connection` in main.swift?

**Comment by amanbolat** [comment]
Ok, i tried again to recreate this error. I frequently refreshed web page after logging in and every 2nd or 3rd refresh had no response from server. Then i continue to refresh and after 20-30 times this error come again. 

I tracked debug flow in xcode, It happens on blocks of code where server wants to restore session -> connects to database for fetching -> close connection ti database cause ERROR
![image](https://cloud.githubusercontent.com/assets/15110242/19778970/aeb3c15a-9cb1-11e6-8ac9-5ffe47499b3b.png)

**Comment by amanbolat** [comment]
@iamjono Today i started debug it again and used query `SELECT * FROM pg_stat_activity;` in psql to find active connections.

**Comment by proyb6** [comment]
@amanbolat Is this error still reproducible?

**Comment by iamjono** [comment]
Closing - this was fixed a while back, was an issue with open states not being closed
